### ISSUE TITLE
ImportError: No module named docutils.core

### ISSUE THREAD

**Issue by jwilk** [jwilk/pydiatra#1]
I saw this on [Travis CI](https://travis-ci.org/jwilk/python-syntax-errors/jobs/382389392):
```console
$ pip install pydiatra $pyflakes
Collecting pydiatra
  Downloading https://files.pythonhosted.org/packages/65/ae/232b72366940a43e722a256d003c40ef0b027bec7ecddf00cf9095de442a/pydiatra-0.12.2.tar.gz (44kB)
    100% |████████████████████████████████| 45kB 5.6MB/s 
[…]
Building wheels for collected packages: pydiatra
  Running setup.py bdist_wheel for pydiatra
  Complete output from command /home/travis/virtualenv/python3.2.6/bin/python -c "import setuptools;__file__='/tmp/pip-build-8h7tlv/pydiatra/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpinu3_dpip-wheel-:
  running bdist_wheel
  running build
  running build_doc
  generating doc/tags.rst from pydiatra/data/tags
  generating doc/pydiatra.1 from doc/tags.rst, doc/manpage.rst
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-8h7tlv/pydiatra/setup.py", line 225, in <module>
      distutils.core.setup(**setup_options)
    […]
    File "/tmp/pip-build-8h7tlv/pydiatra/setup.py", line 152, in run
      self.make_file([tags_rst_path, man_rst_path], man_path, self.make_man, [man_rst_path, man_path])
    File "/opt/python/3.2.6/lib/python3.2/distutils/cmd.py", line 399, in make_file
      self.execute(func, args, exec_msg, level)
    File "/opt/python/3.2.6/lib/python3.2/distutils/cmd.py", line 336, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/opt/python/3.2.6/lib/python3.2/distutils/util.py", line 318, in execute
      func(*args)
    File "/tmp/pip-build-8h7tlv/pydiatra/setup.py", line 125, in make_man
      import docutils.core
  ImportError: No module named docutils.core
  
  ----------------------------------------
  Failed building wheel for pydiatra
```

I don't understand what's going on here.
`doc/tags.rst` has a newer timestamp than `pydiatra/data/tags`, so it should be regenerated:
```console
$ tar --wildcards -tvvf pydiatra-0.12.2.tar.gz '*/doc/tags.rst' '*/pydiatra/data/tags'
-rw-r--r-- root/root     10109 2018-05-15 01:17 pydiatra-0.12.2/doc/tags.rst
-rw-r--r-- root/root     10154 2017-05-15 21:35 pydiatra-0.12.2/pydiatra/data/tags
```

**Comment by jwilk** [comment]
pip didn't preserve timestamps when unpacking tarballs before 8.0.0: https://github.com/pypa/pip/issues/3201
But we can't just upgrade pip, because that version is not compatible with Python 3.2. :-/

**Comment by jwilk** [comment]
We no longer test against Python 3.2 on CI, so let's close this.
